name: 'TryHackMe Badge Workflow'
author: 'Cuong - 1yn3r'
description: 'Gets your tryhackme badge and updates it on your README'

inputs:
  image_path:
    description: 'Path of the image file you want to update'
    default: './assets/1yn3r.png'
    required: false
  username:
    description: 'Try Hack Me username'
    required: true
  committer_username:
    description: 'username of committing bot'
    default: 'thm-1yn3r-bot'
    required: false
  committer_email:
    description: 'email of committing bot'
    default: '1yn3r@thm.bot'
    required: false
  commit_message:
    description: 'message of committing bot'
    default: 'Updated THM profile badge'
    required: false
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'cloud-lightning'
  color: 'red'
